sudo: required

language: go

go_import_path: github.com/frodenas/gcs-resource

services:
  - docker

jobs:
  include:
    - stage: Unit tests
      script: make

    - stage: Integration tests
      if: type != pull_request
      env:
        - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json
        - secure: j2PI4lSeuvVRY2FE0CcDc8O6k+jDq5QUGBPWuoGi3+PM6+f5j5QQjA2T7afsp2bG9e7EQ64n0gB2ks/antXHgViyNJ3nMiCtSfVpUmWHlIC/6dfhUdA+FQzjfSwJ7vhJKXDH81Cin509uSZQ+eHwl+ZSUV/7db6K7RdK7GKzxZr92rhBlBo4l+GC83im/9iWEpj5YNMmxjC2EXxXiW0XebUm2Y0+isYnTrEgcwR6L1XOV8CP30Pwmhk+k5KnbX4rWLhznQwkHZPbc+zjBUIep5mzc7wujwPM+HMb7ohzqYmeGziIAEGv99Rsz71oLoT5sjE/KTiNVRHvZxqws0OWjxsy8uo7eB433Tfm4mU2ctj/mNFsoZ/wWPoDUXA5sXeoWJ6URtnwtjjO3lgoaAx+2Gv2Zm/w9a18O2PNfjO9k9gRSxMl7fkvmiaadz91OSZascfIZqI3M+Z2o8XOIZXH5VIGovY0SfHFCYODybXpWrakuZ01O9cEDAi2zBc2nucgHNJM7ivp0SVwZGi35uiotxkXEtaHisSnSygAL1Vi9UUP9e+iDqR5zY63J0mkeA/LHo+N2Ob0fA1NFzWk/wxx9/0NFgav0Fq2/rIj27PJpzI9n8S9u16vcgkWCyrsmfTvMSsPppG82VwIrlMM6J52u9xiloysFfZel3GzNZwNRcg=
        - secure: pWzKFugsT6DHAh6D5NmNx+4mbsPlNGQdXSvFUfO3nDj3CJ7SSTt+mxAifcFrymPCTc3YnMjXR1u5gldWNcZnYXw5ObUm8+e+HTYhN9dSTLBhczr4+b7p4fJ6D+Ke99PF4HoZirQOHFW169jU4YVpz6yV6WIycWXlgeVBSp3eFdJvCh6FiQN17Ym3POxt8CMuy03QfFnd2qQ9x9XfQliOlsn4ZjCQRJfX7IRAiK31/Lb4cdlyswMcgnN3W/O2Sdeh4b26Rp+OoBRbyeF2rSLN1hfarHbCTMEgaI4HrGFZ5d4nTkVbscMsapufgrBwOsI/HvbEWRK7E1NEubD4isgOGMpZuU4IJgbsegKcf/qAkIJfMfk9VxZpHftBRQ+Va6J4Nv8L5VPngtOfa8Ct3QIUV4MmK+RLzAFoT66iu4qRFQL3WUyRZavKgXZekYcThfF9JfPWhcDQf+FlwJdP9uVMSG6PEzX+GK0vRQG/7c0egcpFBYOlYiM745ZissoFJY8bMT9O0UL4lYtsLUpwBJbp6gnaGFwerGSPPhnKocFF73Z6yeMpcYCAFbPh0RdgLh8PfS9xbduIABuW8F37j0DS9je6AlJ1cQ8pjmYlWa395cAidz2WPR7aZbzgH4xEMTzVYfqqgfxCBYnwN19gG1XDm5iG8KA9eDrTm0sbcDDLPyg=
      script:
        - openssl aes-256-cbc -K $encrypted_901c39c3ea3a_key -iv $encrypted_901c39c3ea3a_iv -in client_secrets.json.enc -out $GOOGLE_APPLICATION_CREDENTIALS -d
        - make integration-tests

    - stage: Build docker image
      env:
        - DOCKER_IMAGE_NAME=frodenas/gcs-resource
        - secure: IQAiDaXuiEYTcon43ujAIxRn0t6xd4BZMH5z1e5rW7ybyMiDNQ3vh0v9mH3l56WocRrQDZzCmWGyeTJOblgNsrqCxmW2j/By6UU+8N/PPE0CgrL+TiCccQZFTzW8GhRGEfmW8WTTDznlAk/oUH10xFpH3bfn9k2NO8PTZKUPYFHxF2hN6tGYvuYMyRoYq7/7Nag2L0luzRsqKDXrM80nFYAh8wL8hSevuslLtG5dYglZP8qrgm/uoHCQqth3Etwdgu6twvqcK5O/cVWzYxyf5fk2R86cdzu0Qb7CimHdFm9mXNnlzqz7HJ96ACL9NEnrpfyJ5koJYZ9BnvmpeZ9S+PdfQJYk9LlGmtEddENowyM9HW6Ef6A5+4IZOaNLf4rX1a43GJEMrhxt+h4frhVIlTbAjjjZmL50XcPR1Y/HuLfcSBAG5hqR7aK9UpmQdj2TmqO6qPfPiy4qVBoDzeL9IdvSvK9Wvb1mx3HycKdeaLlhWwg19uQrkgpKPsvUZ684lSEDAKoWbilFhKLS224rqiJ3wwjX7JLUKn1ade+BSrMNb139ifHOOBgONePIcJ3tj5wFXvhNDZplrBlYmEvCHSJnehIjJAI+NRt3MAEPUSRWNBUj5C9R5Gdd0pzYwhhkuzfKlKsxpVJZEsFIyDHSrvMoXe6XqbyGOSP8/Dpyo9U=
        - secure: MlLxqReBxtqdGQRmoEryBOAxuFDT3mXuoF8T4kmXGniNvy+pOyymUTmTKwXyJZAdW2jVPmjQKiKaOJJFB52/HOIqKYZVFNdY4fjXn6MfiCLZXErVLhYcFHwilnLrJVU1D00kuRafA4GwmG8geisSQgjSW4CkH1uNt8iUq3b4awNnthRsC3kB/tVP3zaqiRIhXz/YPOWTc4mCZK4620yD/qtjQ/s7henPn3oRDLKs1AWUD7HLglhFVM47o8ATj2jBKfgsBwEHj4mGOmsi/YiMQdgEZIZ6ZDpR+bkK42e5Jm1rARh0+BP/Kh7B6d/8z94bPXBPxmRet5bjDRwQTD7Osg3EJFqKO6ubLOnq4vI44v6WmdfYgUUYwWTVNA+YBIjGSNsMIrE7py6/eisF13PHpLubnd1XvYJozxCjbAy+tQDY2TR9JR8GfuNcuBOzSyMwKLJhBDxIAQ9sV0zdBg5C5vI1o+ONlXf+Wchv73Owmwg9oOqw2io4zRZCuEN+C6wEpwKrQKGexQ1h39btH3dV9b+AF6EJ6v0AgrkiuPXv3XlXbZoMLHMK00Yn18NuG40aZfjtyL7Wm6emKi/kJrRxKXNhchb3heyHJ+ye/pRJyppMFfzFCwL26KZCvqP4SCNVY+J+Tqy1+9sLlZA4Gr9uE3S7VFLbw4dCK81nZQutyQg=
      script:
        - make build
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
              DOCKER_IMAGE_TAG=$TRAVIS_BRANCH
            else
              DOCKER_IMAGE_TAG=$TRAVIS_PULL_REQUEST_BRANCH
            fi
          fi
        - make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG
        - docker tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" "$DOCKER_IMAGE_NAME:latest"
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
