---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang


inputs:
- name: gcs-resource
  path: gopath/src/github.com/frodenas/gcs-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/frodenas/gcs-resource/scripts/ci
