---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang

inputs:
  - name: gcs-resource-src
    path: go/src/github.com/frodenas/gcs-resource

outputs:
  - name: built-resource

run:
  path: go/src/github.com/frodenas/gcs-resource/ci/tasks/build.sh
